version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
