version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_KEY=your-app-key
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=your-database-name
      - DB_USERNAME=your-database-username
      - DB_PASSWORD=your-database-password
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your-mysql-root-password
      MYSQL_DATABASE: your-database-name
      MYSQL_USER: your-database-username
      MYSQL_PASSWORD: your-database-password
    ports:
      - "3306:3306"
