name: Deploy Lumen app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install

      - name: Build Lumen app
        run: |
          php artisan cache:clear

      - name: Deploy app
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-public-key: ${{ secrets.SSH_PUBLIC_KEY }}
          server: sylvester@198.58.106.95
          local-path: .env.production
          remote-path: /var/www/html/cap-api/.env
          exclude: vendor/
          args: --exclude vendor/
          run: |
            cd /var/www/html/cap-api


