name: Deploy Lumen app
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          composer install

      - name: Build Lumen app
        run: |
          php artisan cache:clear

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v4.1.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: -rltgoDzvO --delete
          SOURCE: ./ # This is the root directory of your application.
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          TARGET: /var/www/test.loyalty.capplc.com/cap-api # Replace this with the path to your deployment directory on the remote server...
          SCRIPT_AFTER: |
            # Ensure that the deployment user has the necessary permissions on the target directory.
            sudo chown -R ${{ secrets.SSH_USERNAME }}:data-www /var/www/test.loyalty.capplc.com

            # Ensure that the deployment user has the necessary permissions on the target directory.
            sudo chown -R ${{ secrets.SSH_USERNAME }}:data-www /var/www/test.loyalty.capplc.com/cap-api

            sudo chown -R ${{ secrets.SSH_USERNAME }}:data-www /var/www/test.loyalty.capplc.com/cap-api/storage

            # Make sure that the deployment user has write permissions to the target directory.
            sudo chmod -R u+w /var/www/test.loyalty.capplc.com/cap-api

            # Copy .env.production to the deployment directory.
            cp /var/www/html/.env.production /var/www/test.loyalty.capplc.com/cap-api/.env
            echo $RSYNC_STDOUT
