name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: docker.io/${{ secrets.DOCKER_USERNAME }}/loyalty-cap:${{ github.sha }}
    - name: SSH and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: 45.33.19.65
        username: sylvester
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          docker-compose pull
          docker-compose up -d
